### ISSUE TITLE
how did you do this?

### ISSUE THREAD

**Issue by ghost** [antonsynd/flp_utils#1]
Just wondering how you did this? I'm really interested in reverse engineering formats with little-to-no documentation on them, and I had an idea with .flp files. Did you use Ghidra or IDA at all?

Thanks!

**Comment by antonsynd** [comment]
I've never heard of those, but they look useful for sure. Thanks!

What I have done here is really the easiest parts of reverse engineering (version numbers are generally transparently stored, and the file paths of the audio files happen to be stored as unencrypted strings, so they're easy to find).

But the process I went through is about lots of comparisons: create a bunch of files, preferably some that differ minimally, and then either 1) have something you know you can look for (file paths, version numbers) and try to find those (assuming they're not encrypted), or 2) knowing how the files differ when you saved them (like, the pitch of a single MIDI note changed), compare the byte sequences in the files and see what differences could correspond to that change.
